### ISSUE TITLE
Rm repo?

### ISSUE THREAD

**Issue by dandv** [possibilities/meteor-ga#1]
Tons old vs. current solutions, but showed up on the first [GitHub search results page for Meteor analytics](https://github.com/search?utf8=%E2%9C%93&q=meteor+analytics)

**Comment by possibilities** [comment]
Thanks, I added a note to the description. Hopefully people will be keen enough to see that it's 3 years old and not touch it. I almost deleted it but I decided that if I was going to be consistent with this it would mean deleting almost every project i've put on GH and I don't really want to trash so many things just because they're stale. Thanks again!

**Comment by possibilities** [comment]
Actually, if you want to contribute to the bigger problem it might be worth pointing this out to GH. Heavier penalties for repos that haven't been touched when searching?
